# Generated by Django 5.1.1 on 2024-10-06 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_product_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
